# Generated by Django 4.1.3 on 2022-11-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_todo_completed_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
